contactus/urls.py
from . import views
from django.urls import path
app_name='contactus'
urlpatterns=[
    path('',views.contactus_func,name='contactus-func'),
    path('register/', views.user_register,name='user-register'),
    path('login/',views.user_login,name='user-login'),
    path('logout/',views.user_logout,name='user-logout'),
]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('contactus/',include('contactus.urls',namespace='contactus-module')),
    path('home/',include('home.urls',namespace='home-module')),
]

home/urls.py
from . import views
from django.urls import path
app_name='home'
urlpatterns=[
    path('',views.home_func,name='home'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Title
        {% endblock %}
    </title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
{% block head %}

{% endblock %}
</head>
<body>
{% include 'navbar.html' %}
{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home-module:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contactus-module:user-register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contactus-module:user-login' %}">Login</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'contactus-module:user-logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>